# Generated by Django 5.2.6 on 2025-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sluf',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
