# Generated by Django 5.2.6 on 2025-10-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sluf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sluf',
            new_name='slug',
        ),
    ]
