# Generated by Django 5.2.6 on 2025-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_sluf_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='_', max_length=255),
            preserve_default=False,
        ),
    ]
